[project]
name = "trellex"
version = "1.0.0"
description = "Lightweight Personal Kanban Board"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.0.0",
    "pyyaml>=6.0.1",
    "google-auth-oauthlib>=1.2.0",
    "google-api-python-client>=2.114.0",
    "python-dotenv>=1.2.1",
]
